[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.0",
    "numpy>=2.3.3",
    "pillow>=11.3.0",
    "pyproj>=3.7.2",
    "rasterio>=1.4.3",
]
