name: dreamflow_app
description: "Empower field surveyors in Yemen with \"Bina'a Al-Yaman Surveyor,\" an offline-first Flutter app designed for high-precision land surveys, featuring intuitive Arabic UI, real-time GNSS integration, and seamless data synchronization."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  shared_preferences: ^2.0.0
  flutter_secure_storage: ^9.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  flutter_map: ^7.0.2
  geolocator: ^12.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
